spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/project
spring.datasource.username=3CfGqpbqo7NHGyr.root
spring.datasource.password=mJa4AVkk2cCtqyBi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devillets1991@gmail.com
spring.mail.password=wlfgwuqaaseajrmo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.servlet.session.timeout=15m
app.base-url=https://quize-forge.onrender.com
server.port=8081

